sudo: false
language: node_js
before_install:
  - npm install -g grunt-cli
  - npm i jquery@3.1.1 backbone@1.3.3 lodash@4.16.6
node_js:
  - "4"
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
